- hosts: ubuntu
  vars:
    realm: YOUR_SFX_REALM
    serverName: YOUR_SERVER_NAME
    clusterName: YOUR_CLUSTER_NAME
    token: YOUR_SFX_TOKEN
  tasks:
  - name: Download SmartGateway 
    get_url:
      url: https://app.{{ realm }}.signalfx.com/v2/smart-gateway/download/v2.0.4
      dest: /tmp/smart-gateway.gz
      headers:
        X-SF-Token: "{{ token }}"
      mode: '0755'
    register: smartgateway_downloaded

  - name: Unzip SmartGateway
    command: gunzip /tmp/smart-gateway.gz
    when: smartgateway_downloaded['changed'] == true

  - name: Move SmartGateway binary
    command: cp /tmp/smart-gateway /usr/local/bin
    when: smartgateway_downloaded['changed'] == true

  - name: Create SmartGateway directories
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - /var/lib/gateway/etc
      - /var/lib/gateway/logs
      - /var/lib/gateway/data
    when: smartgateway_downloaded['changed'] == true

  - name: Create SmartGateway configuration file
    template:
      src: smartgateway.j2
      dest: /var/lib/gateway/etc/gateway.conf
