- hosts: ubuntu
  vars:
    realm: YOUR_SFX_REALM
    serverName: YOUR_SERVER_NAME
    clusterName: YOUR_CLUSTER_NAME
    token: YOUR_SFX_TOKEN
    version: "v2.0.4"
  tasks:
  - name: Download SmartGateway 
    get_url:
      url: https://app.{{ realm }}.signalfx.com/v2/smart-gateway/download/{{ version }}
      dest: /tmp/smart-gateway-{{ version }}.gz
      headers:
        X-SF-Token: "{{ token }}"
      mode: "0755"
    register: smartgateway_downloaded

  - name: Unzip SmartGateway
    command: gunzip /tmp/smart-gateway-{{ version }}.gz
    when: smartgateway_downloaded['changed'] == true

  - name: Copy SmartGateway binary to /usr/local/bin
    command: cp /tmp/smart-gateway-{{ version }} /usr/local/bin/smart-gateway
    when: smartgateway_downloaded['changed'] == true

  - name: Create SmartGateway directories
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - /var/lib/gateway/etc
      - /var/lib/gateway/logs
      - /var/lib/gateway/data
    when: smartgateway_downloaded['changed'] == true

  - name: Create SmartGateway configuration file
    template:
      src: smartgateway.j2
      dest: /var/lib/gateway/etc/gateway.conf
